version: '3'

networks:
    laravel:

services:
    site:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: csp-webserver
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"
        volumes:
            - ./src:/var/www
            - ./nginx/ssl/:/etc/nginx/ssl/
        environment: 
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: csp-database

        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT:-3306}:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE:-csp}
            MYSQL_USER: ${DB_USER:-cspuser}
            MYSQL_PASSWORD: ${DB_PASS:-secure}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-secure}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www
            - ./php/php.ini-custom:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "9000:9000"
        networks:
            - laravel

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        container_name: csp-search
        environment:
            - node.name=elasticsearch
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - network.bind_host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        depends_on:
            - artisan
            - mysql
        ports:
            - "127.0.0.1:9200:9200"
        networks:
            - laravel

    composer:
        build:
            context: .
            dockerfile: composer.dockerfile
        container_name: composer
        volumes:
            - ./src:/var/www
        working_dir: /var/www
        depends_on:
            - php
        user: laravel
        networks:
            - laravel
        entrypoint: ['composer', '--ignore-platform-reqs']

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql
            - composer
        user: laravel
        working_dir: /var/www
        entrypoint: ['php', '/var/www/artisan']
        networks:
            - laravel
    
volumes:
    dbdata:
        driver: local
    esdata1:
        driver: local
